# Docker Compose for MDEAutomator MCP Server
# Provides both development and production configurations

version: '3.8'

services:
  # Production MCP Server
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VERSION: ${VERSION:-1.0.0}
        VCS_REF: ${VCS_REF:-$(git rev-parse HEAD)}
    image: mdeautomator-mcp:${VERSION:-latest}
    container_name: mdeautomator-mcp-server
    restart: unless-stopped
    environment:      # Azure Function App Configuration
      - FUNCTION_APP_BASE_URL=${FUNCTION_APP_BASE_URL:-https://mdeautomator.azurewebsites.net}
      
      # Authentication Configuration  
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - FUNCTION_KEY=${FUNCTION_KEY}
      - KEY_VAULT_URL=${KEY_VAULT_URL}
      
      # Request Configuration
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-300}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - RETRY_DELAY=${RETRY_DELAY:-1.0}
      
      # Rate Limiting Configuration
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-100}
      - RATE_LIMIT_BURST=${RATE_LIMIT_BURST:-20}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_AUDIT_LOGGING=${ENABLE_AUDIT_LOGGING:-true}
      
      # Security Configuration
      - ENABLE_REQUEST_VALIDATION=${ENABLE_REQUEST_VALIDATION:-true}
      - MAX_DEVICE_IDS_PER_REQUEST=${MAX_DEVICE_IDS_PER_REQUEST:-1000}
      - MAX_INDICATORS_PER_REQUEST=${MAX_INDICATORS_PER_REQUEST:-1000}
    volumes:
      - mcp-logs:/app/logs
      - mcp-data:/app/data
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; import sys; sys.path.insert(0, '/app'); from mcp.function_client import FunctionAppClient; from mcp.config import MCPConfig; asyncio.run(FunctionAppClient(MCPConfig.from_environment()).health_check())"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  # Development MCP Server
  mcp-server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mdeautomator-mcp:dev
    container_name: mdeautomator-mcp-server-dev
    environment:
      - FUNCTION_APP_BASE_URL=${FUNCTION_APP_BASE_URL:-https://mdeautomator-dev.azurewebsites.net}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - FUNCTION_KEY=${FUNCTION_KEY}
      - KEY_VAULT_URL=${KEY_VAULT_URL}
      - LOG_LEVEL=DEBUG
      - ENABLE_AUDIT_LOGGING=true
    volumes:
      - .:/app
      - mcp-logs-dev:/app/logs
      - mcp-data-dev:/app/data
    networks:
      - mcp-network
    ports:
      - "8080:8080"
    profiles:
      - dev

volumes:
  mcp-logs:
    driver: local
  mcp-data:
    driver: local
  mcp-logs-dev:
    driver: local
  mcp-data-dev:
    driver: local

networks:
  mcp-network:
    driver: bridge
